import { useEffect, useState } from 'react';
import Plot from '../plotly.js';
import { CircleAlert, ClipboardCheck, Search, Send, UserRoundCheck } from 'lucide-react';
import { getCases, getLoans, updateCase } from '../api.js';

const money = (amount) => new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 }).format(amount || 0);
const plotConfig = { responsive: true, displayModeBar: false };
const plotLayout = { autosize: true, paper_bgcolor: 'transparent', plot_bgcolor: 'transparent', font: { family: 'DM Sans, sans-serif', color: '#58635f', size: 11 }, margin: { l: 44, r: 12, t: 10, b: 38 }, xaxis: { gridcolor: '#e8ece8' }, yaxis: { gridcolor: '#e8ece8' } };

export default function Loans() {
  const [tab, setTab] = useState('borrowers');
  const [loanData, setLoanData] = useState(null);
  const [caseData, setCaseData] = useState({ items: [], total: 0, status_counts: [] });
  const [type, setType] = useState('');
  const [status, setStatus] = useState('');
  const [search, setSearch] = useState('');
  const [casePage, setCasePage] = useState(0);
  const [selectedCase, setSelectedCase] = useState(null);
  const [assignee, setAssignee] = useState('');
  const [note, setNote] = useState('');
  const [error, setError] = useState('');
  const [notice, setNotice] = useState('');

  const loadLoans = () => getLoans().then(setLoanData).catch((issue) => setError(issue.message));
  const casePageSize = 100;
  const loadCases = () => getCases({ limit: casePageSize, offset: casePage * casePageSize, type, status, search }).then((result) => { setCaseData(result); setSelectedCase((current) => result.items.find((row) => row.case_id === current?.case_id) || result.items[0] || null); }).catch((issue) => setError(issue.message));
  useEffect(() => { loadLoans(); }, []);
  useEffect(() => { loadCases(); }, [type, status, search, casePage]);
  useEffect(() => { setAssignee(selectedCase?.assignee || ''); setNote(''); }, [selectedCase?.case_id]);

  const borrowers = loanData?.borrowers || [];
  const summary = loanData?.summary || {};
  const upcoming = [...borrowers].filter((row) => row.days_to_next_emi <= 14).sort((a, b) => a.days_to_next_emi - b.days_to_next_emi);
  const delayed = [...borrowers].filter((row) => row.delayed_flag).sort((a, b) => b.last_emi_dpd - a.last_emi_dpd);
  const riskBands = ['Low', 'Medium', 'High'].map((band) => ({ band, count: borrowers.filter((row) => row.risk_band === band).length }));

  async function changeCase(patch, message) {
    if (!selectedCase) return;
    try {
      await updateCase(selectedCase.case_id, patch);
      await loadCases();
      setNotice(message);
      setError('');
    } catch (issue) { setError(issue.message); }
  }

  return <section className="page-stack">
    {error && <div className="error-banner"><CircleAlert size={17} /> {error}</div>}{notice && <div className="success-banner"><ClipboardCheck size={16} /> {notice}</div>}
    <div className="stat-grid five-up"><article className="stat-panel"><span>BORROWERS</span><strong>{summary.borrowers ?? '—'}</strong><small>active loan profiles</small></article><article className="stat-panel"><span>HIGH REPAYMENT RISK</span><strong className="text-coral">{summary.high_risk ?? '—'}</strong><small>risk score above 0.65</small></article><article className="stat-panel"><span>MEDIUM RISK</span><strong>{summary.medium_risk ?? '—'}</strong><small>risk score 0.35–0.65</small></article><article className="stat-panel"><span>PORTFOLIO OUTSTANDING</span><strong>{money(summary.outstanding)}</strong><small>across active loans</small></article><article className="stat-panel"><span>CURRENTLY OVERDUE</span><strong>{summary.overdue ?? '—'}</strong><small>borrowers overdue now</small></article></div>
    <div className="section-tabs" role="tablist"><button className={tab === 'borrowers' ? 'selected' : ''} onClick={() => setTab('borrowers')} role="tab">Borrower health</button><button className={tab === 'cases' ? 'selected' : ''} onClick={() => setTab('cases')} role="tab">Intervention queue <span className="tab-count">{caseData.total}</span></button></div>
    {tab === 'borrowers' ? <div className="page-stack">
      <div className="borrower-grid"><article className="chart-panel"><div className="panel-heading"><div><span className="panel-index">01</span><h3>Early-warning signals</h3></div><span className="panel-unit">BORROWERS</span></div><div className="warning-bars">{(loanData?.warning_counts || []).map((row) => <div className="warning-bar-row" key={row.warning}><span>{row.warning}</span><div className="warning-track"><i style={{ width: `${Math.max(2, row.borrowers / Math.max(1, summary.borrowers) * 100)}%` }} /></div><strong>{row.borrowers}</strong></div>)}{loanData && !loanData.warning_counts.length && <p className="empty-state">No active warning signals.</p>}</div></article><article className="chart-panel"><div className="panel-heading"><div><span className="panel-index">02</span><h3>Risk band distribution</h3></div><span className="panel-unit">REPAYMENT MODEL</span></div><Plot data={[{ type: 'bar', x: riskBands.map((row) => row.band), y: riskBands.map((row) => row.count), marker: { color: ['#139b8a', '#d19a2a', '#de5a43'] }, text: riskBands.map((row) => row.count), textposition: 'outside' }]} layout={{ ...plotLayout, height: 260, yaxis: { ...plotLayout.yaxis, rangemode: 'tozero' } }} config={plotConfig} useResizeHandler className="plot" /></article></div>
      <div className="split-tables"><article className="table-panel"><div className="panel-heading"><div><span className="panel-index">03</span><h3>Upcoming payments</h3></div><span className="panel-unit">NEXT 14 DAYS</span></div><div className="table-scroll"><table><thead><tr><th>CUSTOMER</th><th>DUE DATE</th><th>IN</th><th>EMI</th><th>RISK</th></tr></thead><tbody>{upcoming.slice(0, 10).map((row) => <tr key={row.loan_id}><td><strong>{row.name}</strong><small className="cell-subtitle">{row.customer_id}</small></td><td>{row.next_due_date}</td><td>{row.days_to_next_emi} days</td><td>{money(row.emi)}</td><td><span className={`risk-value ${row.risk_band === 'High' ? 'risk-high' : ''}`}>{row.risk_band}</span></td></tr>)}{!upcoming.length && <tr><td colSpan="5" className="empty-state">No payments due within 14 days.</td></tr>}</tbody></table></div></article><article className="table-panel"><div className="panel-heading"><div><span className="panel-index">04</span><h3>Delayed repayments</h3></div><span className="panel-unit">PAST-DUE FIRST</span></div><div className="table-scroll"><table><thead><tr><th>CUSTOMER</th><th>LAST STATUS</th><th>DAYS LATE</th><th>LATE COUNT</th></tr></thead><tbody>{delayed.slice(0, 10).map((row) => <tr key={row.loan_id}><td><strong>{row.name}</strong><small className="cell-subtitle">{row.customer_id}</small></td><td><span className="status-text status-late">{row.last_emi_status}</span></td><td>{row.last_emi_dpd}</td><td>{row.late_count_90d}</td></tr>)}{!delayed.length && <tr><td colSpan="4" className="empty-state">No delayed repayments.</td></tr>}</tbody></table></div></article></div>
      <article className="table-panel"><div className="panel-heading"><div><span className="panel-index">05</span><h3>Borrower risk register</h3></div><span className="panel-unit">SORTED BY RISK SCORE</span></div><div className="table-scroll"><table><thead><tr><th>CUSTOMER / LOAN</th><th>RISK</th><th>BAND</th><th>WARNINGS</th><th>EMI / INCOME</th><th>INCOME Δ60D</th><th>OUTSTANDING</th></tr></thead><tbody>{borrowers.slice(0, 120).map((row) => <tr key={row.loan_id}><td><strong>{row.name}</strong><small className="cell-subtitle">{row.loan_id}</small></td><td><strong className={row.repayment_risk > 0.65 ? 'text-coral' : ''}>{Number(row.repayment_risk).toFixed(2)}</strong></td><td><span className={`risk-band band-${row.risk_band.toLowerCase()}`}>{row.risk_band}</span></td><td className="warning-cell">{row.warnings || '—'}</td><td>{percent(row.emi_to_income)}</td><td className={row.income_change_60d < 0 ? 'text-coral' : ''}>{percent(row.income_change_60d, true)}</td><td>{money(row.outstanding)}</td></tr>)}</tbody></table></div></article>
    </div> : <div className="case-layout">
      <div className="case-main"><div className="case-filters"><label className="search-field"><Search size={15} /><input value={search} onChange={(event) => { setCasePage(0); setSearch(event.target.value); }} placeholder="Search customer or category" /></label><select className="field-select" value={type} onChange={(event) => { setCasePage(0); setType(event.target.value); }}><option value="">All case types</option><option value="fraud">Fraud</option><option value="loan">Loan</option></select><select className="field-select" value={status} onChange={(event) => { setCasePage(0); setStatus(event.target.value); }}><option value="">All statuses</option><option>Open</option><option>In Progress</option><option>Resolved</option></select></div>
        <div className="case-counts">{['Open', 'In Progress', 'Resolved'].map((name) => <span key={name}>{name}<strong>{caseData.status_counts?.find((row) => row.status === name)?.count || 0}</strong></span>)}<span>Matching<strong>{caseData.total}</strong></span></div>
        <div className="case-list">{caseData.items.map((item) => <button key={item.case_id} className={`case-row ${selectedCase?.case_id === item.case_id ? 'selected' : ''}`} onClick={() => setSelectedCase(item)}><span className={`case-type-mark ${item.type}`}>{item.type === 'fraud' ? 'F' : 'L'}</span><span className="case-row-info"><strong>{item.customer_name}</strong><small>{item.type} · {item.category?.replaceAll('_', ' ')}</small></span><span className="case-row-risk">{Number(item.risk_score).toFixed(2)}</span><span className={`status-pill status-${item.status.toLowerCase().replace(' ', '-')}`}>{item.status}</span></button>)}{!caseData.items.length && <p className="empty-state">No cases match these filters.</p>}</div><div className="case-pagination"><span>{casePage * casePageSize + (caseData.items.length ? 1 : 0)}–{Math.min((casePage + 1) * casePageSize, caseData.total)} of {caseData.total}</span><div><button className="text-button" disabled={casePage === 0} onClick={() => setCasePage((value) => Math.max(0, value - 1))}>Previous</button><button className="text-button" disabled={(casePage + 1) * casePageSize >= caseData.total} onClick={() => setCasePage((value) => value + 1)}>Next</button></div></div>
      </div>
      <aside className="case-detail-panel">{selectedCase ? <><div className="case-detail-head"><span className={`case-type-mark ${selectedCase.type}`}>{selectedCase.type === 'fraud' ? 'F' : 'L'}</span><div><span className="eyebrow">CASE #{selectedCase.case_id} · {selectedCase.type.toUpperCase()}</span><h2>{selectedCase.customer_name}</h2><p>{selectedCase.category?.replaceAll('_', ' ')} · {selectedCase.created_at}</p></div></div><div className="case-risk-block"><span>RISK SCORE</span><strong>{Number(selectedCase.risk_score).toFixed(2)}</strong><span>{money(selectedCase.amount)} exposure</span></div><div className="case-copy"><span className="eyebrow">RECOMMENDED ACTION</span><p>{selectedCase.recommended_action}</p></div><div className="case-copy"><span className="eyebrow">CASE SUMMARY</span><p>{selectedCase.summary || 'No summary available.'}</p></div><div className="reason-list">{safeReasons(selectedCase.reasons).map((reason) => <span key={reason}>{reason}</span>)}</div><div className="case-notes"><span className="eyebrow">CASE LOG</span><pre>{selectedCase.notes || 'No notes recorded.'}</pre></div>
        <label className="form-label">ASSIGNEE<input className="text-input" value={assignee} onChange={(event) => setAssignee(event.target.value)} placeholder="Analyst name" /></label><label className="form-label">ADD NOTE<input className="text-input" value={note} onChange={(event) => setNote(event.target.value)} placeholder="Record an action or observation" /></label>
        <div className="case-actions"><button className="primary-button" onClick={() => changeCase({ status: selectedCase.status === 'Open' ? 'In Progress' : selectedCase.status, assignee, note: `Assigned to ${assignee}` }, 'Case assignment saved.')}><UserRoundCheck size={15} /> Assign</button><button className="secondary-button" disabled={!note.trim()} onClick={() => changeCase({ note }, 'Case note added.')}><Send size={14} /> Add note</button><button className="secondary-button" onClick={() => changeCase({ status: 'In Progress', note: 'Reminder sent to customer by SMS and app.' }, 'Reminder logged.')}><Send size={14} /> Reminder</button>{selectedCase.type === 'loan' && <button className="secondary-button" onClick={() => changeCase({ status: 'In Progress', note: `Restructuring offer sent: ${selectedCase.recommended_action}` }, 'Restructuring offer logged.')}><ClipboardCheck size={14} /> Restructure</button>}{selectedCase.type === 'fraud' && <button className="secondary-button" onClick={() => changeCase({ status: 'In Progress', note: 'Escalated to fraud investigation team.' }, 'Case escalated.')}><CircleAlert size={14} /> Escalate</button>}<button className="resolve-button" onClick={() => changeCase({ status: selectedCase.status === 'Resolved' ? 'Open' : 'Resolved', note: selectedCase.status === 'Resolved' ? 'Case reopened.' : 'Case resolved.' }, selectedCase.status === 'Resolved' ? 'Case reopened.' : 'Case resolved.')}>{selectedCase.status === 'Resolved' ? 'Reopen' : 'Resolve'}</button></div></> : <div className="empty-detail">Select a case to review its risk context and actions.</div>}</aside>
    </div>}
    <div className="notice-line"><span className="state-dot" /> Risk bands and interventions are generated from synthetic demo data.</div>
  </section>;
}

function safeReasons(value) { try { return value ? JSON.parse(value) : []; } catch { return []; } }
function percent(value, signed = false) { const number = Number(value || 0) * 100; return `${signed && number > 0 ? '+' : ''}${number.toFixed(0)}%`; }